version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: "my-mongo"
    restart: always
    ports:
      - 1:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - mongo

networks:
  mongo:
